/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/comments": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.comments.id"];
          created_at?: parameters["rowFilter.comments.created_at"];
          scrap_id?: parameters["rowFilter.comments.scrap_id"];
          user_id?: parameters["rowFilter.comments.user_id"];
          body?: parameters["rowFilter.comments.body"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["comments"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** comments */
          comments?: definitions["comments"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.comments.id"];
          created_at?: parameters["rowFilter.comments.created_at"];
          scrap_id?: parameters["rowFilter.comments.scrap_id"];
          user_id?: parameters["rowFilter.comments.user_id"];
          body?: parameters["rowFilter.comments.body"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.comments.id"];
          created_at?: parameters["rowFilter.comments.created_at"];
          scrap_id?: parameters["rowFilter.comments.scrap_id"];
          user_id?: parameters["rowFilter.comments.user_id"];
          body?: parameters["rowFilter.comments.body"];
        };
        body: {
          /** comments */
          comments?: definitions["comments"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/scraps": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.scraps.id"];
          created_at?: parameters["rowFilter.scraps.created_at"];
          title?: parameters["rowFilter.scraps.title"];
          closed_at?: parameters["rowFilter.scraps.closed_at"];
          user_id?: parameters["rowFilter.scraps.user_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["scraps"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** scraps */
          scraps?: definitions["scraps"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.scraps.id"];
          created_at?: parameters["rowFilter.scraps.created_at"];
          title?: parameters["rowFilter.scraps.title"];
          closed_at?: parameters["rowFilter.scraps.closed_at"];
          user_id?: parameters["rowFilter.scraps.user_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.scraps.id"];
          created_at?: parameters["rowFilter.scraps.created_at"];
          title?: parameters["rowFilter.scraps.title"];
          closed_at?: parameters["rowFilter.scraps.closed_at"];
          user_id?: parameters["rowFilter.scraps.user_id"];
        };
        body: {
          /** scraps */
          scraps?: definitions["scraps"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  comments: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    created_at: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    scrap_id: string;
    user_id: string;
    body: string;
  };
  scraps: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    created_at: string;
    title: string;
    closed_at?: string;
    user_id: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** comments */
  "body.comments": definitions["comments"];
  "rowFilter.comments.id": string;
  "rowFilter.comments.created_at": string;
  "rowFilter.comments.scrap_id": string;
  "rowFilter.comments.user_id": string;
  "rowFilter.comments.body": string;
  /** scraps */
  "body.scraps": definitions["scraps"];
  "rowFilter.scraps.id": string;
  "rowFilter.scraps.created_at": string;
  "rowFilter.scraps.title": string;
  "rowFilter.scraps.closed_at": string;
  "rowFilter.scraps.user_id": string;
}

export interface operations {}

export interface external {}
